### ISSUE TITLE
Failed ids validation

### ISSUE THREAD

**Issue by arishinsemen** [CBenghi/Xbim.Xids#10]
https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases/attribute/pass-durations_are_treated_as_strings_1_2.ids

try to upload this file. Suppose that files from oficial IDS repo is valid. Your output is 
![image](https://github.com/CBenghi/Xbim.Xids/assets/112494711/d04f2c13-a3cc-4240-bd04-c4a0bce6c43d)
Where is mistake? Looks like test file is valid

**Comment by andyward** [comment]
IfcTaskTime was new in IFC4 and does not exist in IFC2x3. The IDS spec is defined as `ifcVersion="IFC2X3 IFC4"` so I'd guess that accounts for Errors 103 and 306 - when testing in Ifc2x3

**Comment by andyward** [comment]
The 2nd issue is that there has been some [back](https://github.com/buildingSMART/IDS/issues/144) and [forth](https://github.com/buildingSMART/IDS/issues/187) in the IDS standard over whether Attribute facets should support cardinality (min/maxOccurs). So I think the ids validator expects them not to be present, but the latest samples still do have the minOccurs etc. e.g. the attribute element on line 15 of the file.

There's a [PR ](https://github.com/buildingSMART/IDS/pull/192/files#diff-ef3d252a0eac51bdf03bb1b2778125d156d92367b592c0829b473aa6e577a932) to update the test cases, but don't be surprised if the cardinality makes a re-appearance (which will require the validator to be updated to remove this rule - if it hasn't already).

I edited the IDS file manually to remove Ifc2x3 and the attribute cardinality and it validates clean then.

```xml
<ids xmlns="http://standards.buildingsmart.org/IDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS/ids_05.xsd">
    <info>
        <title>Durations are treated as strings 1/2</title>
    </info>
    <specifications>
        <specification name="Durations are treated as strings 1/2" ifcVersion="IFC4" minOccurs="1" maxOccurs="unbounded">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IFCTASKTIME</simpleValue>
                    </name>
                </entity>
            </applicability>
            <requirements>
                <attribute>
                    <name>
                        <simpleValue>ScheduleDuration</simpleValue>
                    </name>
                    <value>
                        <simpleValue>PT16H</simpleValue>
                    </value>
                </attribute>
            </requirements>
        </specification>
    </specifications>
</ids>

```

**Comment by arishinsemen** [comment]
Thank you for explaining
