### ISSUE TITLE
Unable to deserialise multiple regex patterns in a restriction

### ISSUE THREAD

**Issue by andyward** [CBenghi/Xbim.Xids#15]
If multiple Regex pattern restrictions are to be supported in IDS - as per [IDS285](https://github.com/buildingSMART/IDS/issues/285) we need to update the IO to support loading multiple patterns. We have a failing test demonstrating the issue at:

https://github.com/CBenghi/Xbim.Xids/blob/d8037fff0c1ab5cbb232a7c9e5cafbdb1e626a9d/Xbim.InformationSpecifications.NewTests/IoTests.cs#L80

The current state is:
- [x] We can save multiple patterns in a restriction to BS XML IDS
- [x] We can verify multiple patterns in a restriction (standard feature of a ValueConstraint)
- [x] We **cannot** load multiple patterns from a BS IDS file. Only the last entry is ever loaded
- [x] JSON IO - untested

> **Sidenote on verification of multiple patterns**
According to the [XSD standards on patterns](https://www.w3.org/TR/2011/CR-xmlschema11-2-20110721/datatypes.html#dc-pattern) we should build a compound regex statement for all patterns using the '|' (OR) separator in regex. But our implementation maintains a regex per pattern which we execute individually, which has the same outcome but may consume more resources. In order to keep file round-tripping and the execution code simple this feels like a fair compromise.

> **Sidenote on other restrictions**
What would be the expected behaviour when other constraint types are provided multiple times? E.g. multiple _minLength_s, structure constraints etc?

**Comment by CBenghi** [comment]
I'll chip in on this in the coming days.

**Comment by andyward** [comment]
One other consideration: I believe it's possible to combine restriction child elements of different types. E.g. it seems according to XSD you can have something like this:
```xml
<xs:restriction base="xs:string">
	<xs:pattern value="A.*" />
	<xs:maxLength value="10"/>
</xs:restriction>
```
... which feels like it opens a whole load of complexity. E.g. is it sensible to have both enum and Patterns in a single restriction?
