### ISSUE TITLE
Clarify Generator licence

### ISSUE THREAD

**Issue by andyward** [CBenghi/Xbim.Xids#2]
Hi Claudio

Can you confirm if the licence on Xbim.InformationSpecifications.Generator is correct? The main repo is CDDL but the sub-project indicates it's under a specific licence. I think you mentioned this may be an oversight?

https://github.com/CBenghi/Xbim.Xids/blob/main/Xbim.InformationSpecifications.Generator/LICENSE.md

**Comment by CBenghi** [comment]
It is an oversight.
I'll fix it today.
Claudio

**Comment by CBenghi** [comment]
Fixed in: https://github.com/CBenghi/Xbim.Xids/commit/65c893a6b94a412a523b73c664bac393cf98b753
